// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: pb/search_req.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Com.Youku.Server.Pb {

  /// <summary>Holder for reflection information generated from pb/search_req.proto</summary>
  public static partial class SearchReqReflection {

    #region Descriptor
    /// <summary>File descriptor for pb/search_req.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SearchReqReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNwYi9zZWFyY2hfcmVxLnByb3RvEhNjb20ueW91a3Uuc2VydmVyLnBiIukB",
            "Cg1TZWFyY2hSZXF1ZXN0Eg0KBXF1ZXJ5GAEgASgJEhEKCWF2YWlsYWJsZRgC",
            "IAEoCBIQCghkaXN0YW5jZRgDIAEoAhIQCghsb2NhdGlvbhgEIAEoARIOCgZv",
            "ZmZzZXQYBSABKAYSGAoLcGFnZV9udW1iZXIYBiABKAVIAIgBARIcCg9yZXN1",
            "bHRfcGVyX3BhZ2UYByABKA1IAYgBARIXCgpleHRyYV9kYXRhGAggASgMSAKI",
            "AQFCDgoMX3BhZ2VfbnVtYmVyQhIKEF9yZXN1bHRfcGVyX3BhZ2VCDQoLX2V4",
            "dHJhX2RhdGFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Youku.Server.Pb.SearchRequest), global::Com.Youku.Server.Pb.SearchRequest.Parser, new[]{ "Query", "Available", "Distance", "Location", "Offset", "PageNumber", "ResultPerPage", "ExtraData" }, new[]{ "PageNumber", "ResultPerPage", "ExtraData" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class SearchRequest : pb::IMessage<SearchRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SearchRequest> _parser = new pb::MessageParser<SearchRequest>(() => new SearchRequest());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SearchRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Youku.Server.Pb.SearchReqReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SearchRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SearchRequest(SearchRequest other) : this() {
      _hasBits0 = other._hasBits0;
      query_ = other.query_;
      available_ = other.available_;
      distance_ = other.distance_;
      location_ = other.location_;
      offset_ = other.offset_;
      pageNumber_ = other.pageNumber_;
      resultPerPage_ = other.resultPerPage_;
      extraData_ = other.extraData_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SearchRequest Clone() {
      return new SearchRequest(this);
    }

    /// <summary>Field number for the "query" field.</summary>
    public const int QueryFieldNumber = 1;
    private string query_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Query {
      get { return query_; }
      set {
        query_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "available" field.</summary>
    public const int AvailableFieldNumber = 2;
    private bool available_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Available {
      get { return available_; }
      set {
        available_ = value;
      }
    }

    /// <summary>Field number for the "distance" field.</summary>
    public const int DistanceFieldNumber = 3;
    private float distance_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Distance {
      get { return distance_; }
      set {
        distance_ = value;
      }
    }

    /// <summary>Field number for the "location" field.</summary>
    public const int LocationFieldNumber = 4;
    private double location_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Location {
      get { return location_; }
      set {
        location_ = value;
      }
    }

    /// <summary>Field number for the "offset" field.</summary>
    public const int OffsetFieldNumber = 5;
    private ulong offset_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Offset {
      get { return offset_; }
      set {
        offset_ = value;
      }
    }

    /// <summary>Field number for the "page_number" field.</summary>
    public const int PageNumberFieldNumber = 6;
    private int pageNumber_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PageNumber {
      get { if ((_hasBits0 & 1) != 0) { return pageNumber_; } else { return 0; } }
      set {
        _hasBits0 |= 1;
        pageNumber_ = value;
      }
    }
    /// <summary>Gets whether the "page_number" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPageNumber {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "page_number" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPageNumber() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "result_per_page" field.</summary>
    public const int ResultPerPageFieldNumber = 7;
    private uint resultPerPage_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ResultPerPage {
      get { if ((_hasBits0 & 2) != 0) { return resultPerPage_; } else { return 0; } }
      set {
        _hasBits0 |= 2;
        resultPerPage_ = value;
      }
    }
    /// <summary>Gets whether the "result_per_page" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasResultPerPage {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "result_per_page" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearResultPerPage() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "extra_data" field.</summary>
    public const int ExtraDataFieldNumber = 8;
    private pb::ByteString extraData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString ExtraData {
      get { return extraData_ ?? pb::ByteString.Empty; }
      set {
        extraData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "extra_data" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasExtraData {
      get { return extraData_ != null; }
    }
    /// <summary>Clears the value of the "extra_data" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearExtraData() {
      extraData_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SearchRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SearchRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Query != other.Query) return false;
      if (Available != other.Available) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Distance, other.Distance)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Location, other.Location)) return false;
      if (Offset != other.Offset) return false;
      if (PageNumber != other.PageNumber) return false;
      if (ResultPerPage != other.ResultPerPage) return false;
      if (ExtraData != other.ExtraData) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Query.Length != 0) hash ^= Query.GetHashCode();
      if (Available != false) hash ^= Available.GetHashCode();
      if (Distance != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Distance);
      if (Location != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Location);
      if (Offset != 0UL) hash ^= Offset.GetHashCode();
      if (HasPageNumber) hash ^= PageNumber.GetHashCode();
      if (HasResultPerPage) hash ^= ResultPerPage.GetHashCode();
      if (HasExtraData) hash ^= ExtraData.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Query.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Query);
      }
      if (Available != false) {
        output.WriteRawTag(16);
        output.WriteBool(Available);
      }
      if (Distance != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(Distance);
      }
      if (Location != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(Location);
      }
      if (Offset != 0UL) {
        output.WriteRawTag(41);
        output.WriteFixed64(Offset);
      }
      if (HasPageNumber) {
        output.WriteRawTag(48);
        output.WriteInt32(PageNumber);
      }
      if (HasResultPerPage) {
        output.WriteRawTag(56);
        output.WriteUInt32(ResultPerPage);
      }
      if (HasExtraData) {
        output.WriteRawTag(66);
        output.WriteBytes(ExtraData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Query.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Query);
      }
      if (Available != false) {
        output.WriteRawTag(16);
        output.WriteBool(Available);
      }
      if (Distance != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(Distance);
      }
      if (Location != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(Location);
      }
      if (Offset != 0UL) {
        output.WriteRawTag(41);
        output.WriteFixed64(Offset);
      }
      if (HasPageNumber) {
        output.WriteRawTag(48);
        output.WriteInt32(PageNumber);
      }
      if (HasResultPerPage) {
        output.WriteRawTag(56);
        output.WriteUInt32(ResultPerPage);
      }
      if (HasExtraData) {
        output.WriteRawTag(66);
        output.WriteBytes(ExtraData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Query.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Query);
      }
      if (Available != false) {
        size += 1 + 1;
      }
      if (Distance != 0F) {
        size += 1 + 4;
      }
      if (Location != 0D) {
        size += 1 + 8;
      }
      if (Offset != 0UL) {
        size += 1 + 8;
      }
      if (HasPageNumber) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PageNumber);
      }
      if (HasResultPerPage) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ResultPerPage);
      }
      if (HasExtraData) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(ExtraData);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SearchRequest other) {
      if (other == null) {
        return;
      }
      if (other.Query.Length != 0) {
        Query = other.Query;
      }
      if (other.Available != false) {
        Available = other.Available;
      }
      if (other.Distance != 0F) {
        Distance = other.Distance;
      }
      if (other.Location != 0D) {
        Location = other.Location;
      }
      if (other.Offset != 0UL) {
        Offset = other.Offset;
      }
      if (other.HasPageNumber) {
        PageNumber = other.PageNumber;
      }
      if (other.HasResultPerPage) {
        ResultPerPage = other.ResultPerPage;
      }
      if (other.HasExtraData) {
        ExtraData = other.ExtraData;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Query = input.ReadString();
            break;
          }
          case 16: {
            Available = input.ReadBool();
            break;
          }
          case 29: {
            Distance = input.ReadFloat();
            break;
          }
          case 33: {
            Location = input.ReadDouble();
            break;
          }
          case 41: {
            Offset = input.ReadFixed64();
            break;
          }
          case 48: {
            PageNumber = input.ReadInt32();
            break;
          }
          case 56: {
            ResultPerPage = input.ReadUInt32();
            break;
          }
          case 66: {
            ExtraData = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Query = input.ReadString();
            break;
          }
          case 16: {
            Available = input.ReadBool();
            break;
          }
          case 29: {
            Distance = input.ReadFloat();
            break;
          }
          case 33: {
            Location = input.ReadDouble();
            break;
          }
          case 41: {
            Offset = input.ReadFixed64();
            break;
          }
          case 48: {
            PageNumber = input.ReadInt32();
            break;
          }
          case 56: {
            ResultPerPage = input.ReadUInt32();
            break;
          }
          case 66: {
            ExtraData = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
