// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb/search_req.proto

package com.youku.server.pb;

public final class SearchReq {
  private SearchReq() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SearchRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.youku.server.pb.SearchRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string query = 1;</code>
     * @return The query.
     */
    java.lang.String getQuery();
    /**
     * <code>string query = 1;</code>
     * @return The bytes for query.
     */
    com.google.protobuf.ByteString
        getQueryBytes();

    /**
     * <code>bool available = 2;</code>
     * @return The available.
     */
    boolean getAvailable();

    /**
     * <code>float distance = 3;</code>
     * @return The distance.
     */
    float getDistance();

    /**
     * <code>double location = 4;</code>
     * @return The location.
     */
    double getLocation();

    /**
     * <code>fixed64 offset = 5;</code>
     * @return The offset.
     */
    long getOffset();

    /**
     * <code>optional int32 page_number = 6;</code>
     * @return Whether the pageNumber field is set.
     */
    boolean hasPageNumber();
    /**
     * <code>optional int32 page_number = 6;</code>
     * @return The pageNumber.
     */
    int getPageNumber();

    /**
     * <code>optional uint32 result_per_page = 7;</code>
     * @return Whether the resultPerPage field is set.
     */
    boolean hasResultPerPage();
    /**
     * <code>optional uint32 result_per_page = 7;</code>
     * @return The resultPerPage.
     */
    int getResultPerPage();

    /**
     * <code>optional bytes extra_data = 8;</code>
     * @return Whether the extraData field is set.
     */
    boolean hasExtraData();
    /**
     * <code>optional bytes extra_data = 8;</code>
     * @return The extraData.
     */
    com.google.protobuf.ByteString getExtraData();
  }
  /**
   * Protobuf type {@code com.youku.server.pb.SearchRequest}
   */
  public static final class SearchRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.youku.server.pb.SearchRequest)
      SearchRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SearchRequest.newBuilder() to construct.
    private SearchRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SearchRequest() {
      query_ = "";
      extraData_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SearchRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SearchRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              query_ = s;
              break;
            }
            case 16: {

              available_ = input.readBool();
              break;
            }
            case 29: {

              distance_ = input.readFloat();
              break;
            }
            case 33: {

              location_ = input.readDouble();
              break;
            }
            case 41: {

              offset_ = input.readFixed64();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000001;
              pageNumber_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000002;
              resultPerPage_ = input.readUInt32();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000004;
              extraData_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.youku.server.pb.SearchReq.internal_static_com_youku_server_pb_SearchRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.youku.server.pb.SearchReq.internal_static_com_youku_server_pb_SearchRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.youku.server.pb.SearchReq.SearchRequest.class, com.youku.server.pb.SearchReq.SearchRequest.Builder.class);
    }

    private int bitField0_;
    public static final int QUERY_FIELD_NUMBER = 1;
    private volatile java.lang.Object query_;
    /**
     * <code>string query = 1;</code>
     * @return The query.
     */
    @java.lang.Override
    public java.lang.String getQuery() {
      java.lang.Object ref = query_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        query_ = s;
        return s;
      }
    }
    /**
     * <code>string query = 1;</code>
     * @return The bytes for query.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getQueryBytes() {
      java.lang.Object ref = query_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        query_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AVAILABLE_FIELD_NUMBER = 2;
    private boolean available_;
    /**
     * <code>bool available = 2;</code>
     * @return The available.
     */
    @java.lang.Override
    public boolean getAvailable() {
      return available_;
    }

    public static final int DISTANCE_FIELD_NUMBER = 3;
    private float distance_;
    /**
     * <code>float distance = 3;</code>
     * @return The distance.
     */
    @java.lang.Override
    public float getDistance() {
      return distance_;
    }

    public static final int LOCATION_FIELD_NUMBER = 4;
    private double location_;
    /**
     * <code>double location = 4;</code>
     * @return The location.
     */
    @java.lang.Override
    public double getLocation() {
      return location_;
    }

    public static final int OFFSET_FIELD_NUMBER = 5;
    private long offset_;
    /**
     * <code>fixed64 offset = 5;</code>
     * @return The offset.
     */
    @java.lang.Override
    public long getOffset() {
      return offset_;
    }

    public static final int PAGE_NUMBER_FIELD_NUMBER = 6;
    private int pageNumber_;
    /**
     * <code>optional int32 page_number = 6;</code>
     * @return Whether the pageNumber field is set.
     */
    @java.lang.Override
    public boolean hasPageNumber() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int32 page_number = 6;</code>
     * @return The pageNumber.
     */
    @java.lang.Override
    public int getPageNumber() {
      return pageNumber_;
    }

    public static final int RESULT_PER_PAGE_FIELD_NUMBER = 7;
    private int resultPerPage_;
    /**
     * <code>optional uint32 result_per_page = 7;</code>
     * @return Whether the resultPerPage field is set.
     */
    @java.lang.Override
    public boolean hasResultPerPage() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional uint32 result_per_page = 7;</code>
     * @return The resultPerPage.
     */
    @java.lang.Override
    public int getResultPerPage() {
      return resultPerPage_;
    }

    public static final int EXTRA_DATA_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString extraData_;
    /**
     * <code>optional bytes extra_data = 8;</code>
     * @return Whether the extraData field is set.
     */
    @java.lang.Override
    public boolean hasExtraData() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional bytes extra_data = 8;</code>
     * @return The extraData.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getExtraData() {
      return extraData_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(query_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, query_);
      }
      if (available_ != false) {
        output.writeBool(2, available_);
      }
      if (java.lang.Float.floatToRawIntBits(distance_) != 0) {
        output.writeFloat(3, distance_);
      }
      if (java.lang.Double.doubleToRawLongBits(location_) != 0) {
        output.writeDouble(4, location_);
      }
      if (offset_ != 0L) {
        output.writeFixed64(5, offset_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(6, pageNumber_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeUInt32(7, resultPerPage_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeBytes(8, extraData_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(query_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, query_);
      }
      if (available_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, available_);
      }
      if (java.lang.Float.floatToRawIntBits(distance_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, distance_);
      }
      if (java.lang.Double.doubleToRawLongBits(location_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, location_);
      }
      if (offset_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(5, offset_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, pageNumber_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(7, resultPerPage_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, extraData_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.youku.server.pb.SearchReq.SearchRequest)) {
        return super.equals(obj);
      }
      com.youku.server.pb.SearchReq.SearchRequest other = (com.youku.server.pb.SearchReq.SearchRequest) obj;

      if (!getQuery()
          .equals(other.getQuery())) return false;
      if (getAvailable()
          != other.getAvailable()) return false;
      if (java.lang.Float.floatToIntBits(getDistance())
          != java.lang.Float.floatToIntBits(
              other.getDistance())) return false;
      if (java.lang.Double.doubleToLongBits(getLocation())
          != java.lang.Double.doubleToLongBits(
              other.getLocation())) return false;
      if (getOffset()
          != other.getOffset()) return false;
      if (hasPageNumber() != other.hasPageNumber()) return false;
      if (hasPageNumber()) {
        if (getPageNumber()
            != other.getPageNumber()) return false;
      }
      if (hasResultPerPage() != other.hasResultPerPage()) return false;
      if (hasResultPerPage()) {
        if (getResultPerPage()
            != other.getResultPerPage()) return false;
      }
      if (hasExtraData() != other.hasExtraData()) return false;
      if (hasExtraData()) {
        if (!getExtraData()
            .equals(other.getExtraData())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + QUERY_FIELD_NUMBER;
      hash = (53 * hash) + getQuery().hashCode();
      hash = (37 * hash) + AVAILABLE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getAvailable());
      hash = (37 * hash) + DISTANCE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getDistance());
      hash = (37 * hash) + LOCATION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getLocation()));
      hash = (37 * hash) + OFFSET_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getOffset());
      if (hasPageNumber()) {
        hash = (37 * hash) + PAGE_NUMBER_FIELD_NUMBER;
        hash = (53 * hash) + getPageNumber();
      }
      if (hasResultPerPage()) {
        hash = (37 * hash) + RESULT_PER_PAGE_FIELD_NUMBER;
        hash = (53 * hash) + getResultPerPage();
      }
      if (hasExtraData()) {
        hash = (37 * hash) + EXTRA_DATA_FIELD_NUMBER;
        hash = (53 * hash) + getExtraData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.youku.server.pb.SearchReq.SearchRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.youku.server.pb.SearchReq.SearchRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.youku.server.pb.SearchReq.SearchRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.youku.server.pb.SearchReq.SearchRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.youku.server.pb.SearchReq.SearchRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.youku.server.pb.SearchReq.SearchRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.youku.server.pb.SearchReq.SearchRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.youku.server.pb.SearchReq.SearchRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.youku.server.pb.SearchReq.SearchRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.youku.server.pb.SearchReq.SearchRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.youku.server.pb.SearchReq.SearchRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.youku.server.pb.SearchReq.SearchRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.youku.server.pb.SearchReq.SearchRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.youku.server.pb.SearchRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.youku.server.pb.SearchRequest)
        com.youku.server.pb.SearchReq.SearchRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.youku.server.pb.SearchReq.internal_static_com_youku_server_pb_SearchRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.youku.server.pb.SearchReq.internal_static_com_youku_server_pb_SearchRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.youku.server.pb.SearchReq.SearchRequest.class, com.youku.server.pb.SearchReq.SearchRequest.Builder.class);
      }

      // Construct using com.youku.server.pb.SearchReq.SearchRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        query_ = "";

        available_ = false;

        distance_ = 0F;

        location_ = 0D;

        offset_ = 0L;

        pageNumber_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        resultPerPage_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        extraData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.youku.server.pb.SearchReq.internal_static_com_youku_server_pb_SearchRequest_descriptor;
      }

      @java.lang.Override
      public com.youku.server.pb.SearchReq.SearchRequest getDefaultInstanceForType() {
        return com.youku.server.pb.SearchReq.SearchRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.youku.server.pb.SearchReq.SearchRequest build() {
        com.youku.server.pb.SearchReq.SearchRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.youku.server.pb.SearchReq.SearchRequest buildPartial() {
        com.youku.server.pb.SearchReq.SearchRequest result = new com.youku.server.pb.SearchReq.SearchRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.query_ = query_;
        result.available_ = available_;
        result.distance_ = distance_;
        result.location_ = location_;
        result.offset_ = offset_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.pageNumber_ = pageNumber_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.resultPerPage_ = resultPerPage_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.extraData_ = extraData_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.youku.server.pb.SearchReq.SearchRequest) {
          return mergeFrom((com.youku.server.pb.SearchReq.SearchRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.youku.server.pb.SearchReq.SearchRequest other) {
        if (other == com.youku.server.pb.SearchReq.SearchRequest.getDefaultInstance()) return this;
        if (!other.getQuery().isEmpty()) {
          query_ = other.query_;
          onChanged();
        }
        if (other.getAvailable() != false) {
          setAvailable(other.getAvailable());
        }
        if (other.getDistance() != 0F) {
          setDistance(other.getDistance());
        }
        if (other.getLocation() != 0D) {
          setLocation(other.getLocation());
        }
        if (other.getOffset() != 0L) {
          setOffset(other.getOffset());
        }
        if (other.hasPageNumber()) {
          setPageNumber(other.getPageNumber());
        }
        if (other.hasResultPerPage()) {
          setResultPerPage(other.getResultPerPage());
        }
        if (other.hasExtraData()) {
          setExtraData(other.getExtraData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.youku.server.pb.SearchReq.SearchRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.youku.server.pb.SearchReq.SearchRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object query_ = "";
      /**
       * <code>string query = 1;</code>
       * @return The query.
       */
      public java.lang.String getQuery() {
        java.lang.Object ref = query_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          query_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string query = 1;</code>
       * @return The bytes for query.
       */
      public com.google.protobuf.ByteString
          getQueryBytes() {
        java.lang.Object ref = query_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          query_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string query = 1;</code>
       * @param value The query to set.
       * @return This builder for chaining.
       */
      public Builder setQuery(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        query_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string query = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearQuery() {
        
        query_ = getDefaultInstance().getQuery();
        onChanged();
        return this;
      }
      /**
       * <code>string query = 1;</code>
       * @param value The bytes for query to set.
       * @return This builder for chaining.
       */
      public Builder setQueryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        query_ = value;
        onChanged();
        return this;
      }

      private boolean available_ ;
      /**
       * <code>bool available = 2;</code>
       * @return The available.
       */
      @java.lang.Override
      public boolean getAvailable() {
        return available_;
      }
      /**
       * <code>bool available = 2;</code>
       * @param value The available to set.
       * @return This builder for chaining.
       */
      public Builder setAvailable(boolean value) {
        
        available_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool available = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAvailable() {
        
        available_ = false;
        onChanged();
        return this;
      }

      private float distance_ ;
      /**
       * <code>float distance = 3;</code>
       * @return The distance.
       */
      @java.lang.Override
      public float getDistance() {
        return distance_;
      }
      /**
       * <code>float distance = 3;</code>
       * @param value The distance to set.
       * @return This builder for chaining.
       */
      public Builder setDistance(float value) {
        
        distance_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float distance = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDistance() {
        
        distance_ = 0F;
        onChanged();
        return this;
      }

      private double location_ ;
      /**
       * <code>double location = 4;</code>
       * @return The location.
       */
      @java.lang.Override
      public double getLocation() {
        return location_;
      }
      /**
       * <code>double location = 4;</code>
       * @param value The location to set.
       * @return This builder for chaining.
       */
      public Builder setLocation(double value) {
        
        location_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double location = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearLocation() {
        
        location_ = 0D;
        onChanged();
        return this;
      }

      private long offset_ ;
      /**
       * <code>fixed64 offset = 5;</code>
       * @return The offset.
       */
      @java.lang.Override
      public long getOffset() {
        return offset_;
      }
      /**
       * <code>fixed64 offset = 5;</code>
       * @param value The offset to set.
       * @return This builder for chaining.
       */
      public Builder setOffset(long value) {
        
        offset_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>fixed64 offset = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearOffset() {
        
        offset_ = 0L;
        onChanged();
        return this;
      }

      private int pageNumber_ ;
      /**
       * <code>optional int32 page_number = 6;</code>
       * @return Whether the pageNumber field is set.
       */
      @java.lang.Override
      public boolean hasPageNumber() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional int32 page_number = 6;</code>
       * @return The pageNumber.
       */
      @java.lang.Override
      public int getPageNumber() {
        return pageNumber_;
      }
      /**
       * <code>optional int32 page_number = 6;</code>
       * @param value The pageNumber to set.
       * @return This builder for chaining.
       */
      public Builder setPageNumber(int value) {
        bitField0_ |= 0x00000001;
        pageNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 page_number = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearPageNumber() {
        bitField0_ = (bitField0_ & ~0x00000001);
        pageNumber_ = 0;
        onChanged();
        return this;
      }

      private int resultPerPage_ ;
      /**
       * <code>optional uint32 result_per_page = 7;</code>
       * @return Whether the resultPerPage field is set.
       */
      @java.lang.Override
      public boolean hasResultPerPage() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional uint32 result_per_page = 7;</code>
       * @return The resultPerPage.
       */
      @java.lang.Override
      public int getResultPerPage() {
        return resultPerPage_;
      }
      /**
       * <code>optional uint32 result_per_page = 7;</code>
       * @param value The resultPerPage to set.
       * @return This builder for chaining.
       */
      public Builder setResultPerPage(int value) {
        bitField0_ |= 0x00000002;
        resultPerPage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 result_per_page = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearResultPerPage() {
        bitField0_ = (bitField0_ & ~0x00000002);
        resultPerPage_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString extraData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes extra_data = 8;</code>
       * @return Whether the extraData field is set.
       */
      @java.lang.Override
      public boolean hasExtraData() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional bytes extra_data = 8;</code>
       * @return The extraData.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getExtraData() {
        return extraData_;
      }
      /**
       * <code>optional bytes extra_data = 8;</code>
       * @param value The extraData to set.
       * @return This builder for chaining.
       */
      public Builder setExtraData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        extraData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes extra_data = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearExtraData() {
        bitField0_ = (bitField0_ & ~0x00000004);
        extraData_ = getDefaultInstance().getExtraData();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.youku.server.pb.SearchRequest)
    }

    // @@protoc_insertion_point(class_scope:com.youku.server.pb.SearchRequest)
    private static final com.youku.server.pb.SearchReq.SearchRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.youku.server.pb.SearchReq.SearchRequest();
    }

    public static com.youku.server.pb.SearchReq.SearchRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SearchRequest>
        PARSER = new com.google.protobuf.AbstractParser<SearchRequest>() {
      @java.lang.Override
      public SearchRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SearchRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SearchRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SearchRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.youku.server.pb.SearchReq.SearchRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_youku_server_pb_SearchRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_youku_server_pb_SearchRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023pb/search_req.proto\022\023com.youku.server." +
      "pb\"\351\001\n\rSearchRequest\022\r\n\005query\030\001 \001(\t\022\021\n\ta" +
      "vailable\030\002 \001(\010\022\020\n\010distance\030\003 \001(\002\022\020\n\010loca" +
      "tion\030\004 \001(\001\022\016\n\006offset\030\005 \001(\006\022\030\n\013page_numbe" +
      "r\030\006 \001(\005H\000\210\001\001\022\034\n\017result_per_page\030\007 \001(\rH\001\210" +
      "\001\001\022\027\n\nextra_data\030\010 \001(\014H\002\210\001\001B\016\n\014_page_num" +
      "berB\022\n\020_result_per_pageB\r\n\013_extra_datab\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_youku_server_pb_SearchRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_youku_server_pb_SearchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_youku_server_pb_SearchRequest_descriptor,
        new java.lang.String[] { "Query", "Available", "Distance", "Location", "Offset", "PageNumber", "ResultPerPage", "ExtraData", "PageNumber", "ResultPerPage", "ExtraData", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
